### ISSUE TITLE
Patch masks

### ISSUE THREAD

**Issue by lgarrison** [bd-j/forcepho#27]
Our patches may not always be rectangular; they may have ragged edges/irregular borders.  We will indicate masked regions with a pixel bitmask.  The patch in `forcepho/patch.py` is set up to take a pixel mask but currently does nothing with it.  We probably will still send the masked regions to the GPU but indicate them with `ierr = 0`.

**Comment by bd-j** [comment]
The `Region` class introduced in #41 contains logic for choosing only superpixels within a region on the sky.  I think that accomplishes the goal of patch masks described here.
